service: medical-appointments
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    DYNAMODB_TABLE: ${self:service}-${sls:stage}

functions:
  healthCheck:
    handler: src/handlers/health.handler
    events:
      - httpApi:
          path: /health
          method: GET